### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TobyMot** [raspberrypi/rpicam-apps#632]
**Describe the bug**

**Bug report**
Please use the ``camera-bug-report`` tool to create a bug report, and upload it here.

The bug report tool uses the following syntax:

```
camera-bug-report -t <timeout in seconds> -o <output file> -c "<rpicam-app command>"
```

For example,

```
camera-bug-report -t 5 -o bug.txt -c "rpicam-still -t 1000 -o test.jpg"
```
will attempt to run rpicam-still and timeout after 5 seconds if the application has stalled. The script will generate a ``bug.txt`` file that captures all the output logs and system state to help us debug the issue.

You can also run without a timeout:

```
camera-bug-report -o bug.txt -c "rpicam-vid -t 0 -o test.264"
```
This will run ``rpicam-vid`` indefinitely until either you press ``Ctrl+C`` or the application terminates, after which the necessary output logs and system state will be captured.

If you cannot run your application through the ``camera-bug-report`` tool, run it without the ``-c`` command line argument **after running the camera application.**  In these cases, please also provide the command line used to run the application, as well as any output generated during the run.

**Additional context**

**Comment by TobyMot** [comment]
I have a new raspberry pi 4B and bought two Pi cameras to develop an application that would use openCV, when I can get some images that is.   The pi is loaded and updated, upgraded with the Debian Bookworm distro.  I never get to see a camera config menu on the Raspi-config  menu but I resume this is now deprecated so the raspberrypi.org website is well out of date or have I got the wrong distro. 

I managed to capture some images with an openCV python script yesterday but today using Libcamera or rpicam with either camera and a different machine with the same setup I captured nothing except these error messages. I checked and reset the cables several times since this seems obvious but without any capture. 

is it cables ?
[bug.txt](https://github.com/raspberrypi/rpicam-apps/files/14014061/bug.txt)
[bug2.txt](https://github.com/raspberrypi/rpicam-apps/files/14014062/bug2.txt)

I hope you can help

**Comment by TobyMot** [comment]
I just tried again and the error comes up so  quickly it cannot have run a timeout.  all the dev/video* files are empty can I fix this.

**Comment by naushir** [comment]
Both logs show a camera hardware timeout occurring.  Can you try re-seating the connector cable on both ends and try again.  Failing that, it might point to a hardware issue on either the sensor board or the Pi camera connector.

**Comment by naushir** [comment]
Any update on this?  If not, I'll close this down shortly.
