### ISSUE TITLE
Can rpicam-still save a 16-bit png file when the CMOS support 10 or 12-bit?

### ISSUE THREAD

**Issue by VisionShilin** [raspberrypi/rpicam-apps#639]
Can rpicam-still save a 16-bit png file when the CMOS support 10 or 12-bit ?
The current png_save function only saves a 8-bit png file.

**Comment by naushir** [comment]
Once https://github.com/raspberrypi/rpicam-apps/pull/599 is merged (together with the accompanying libcamera change), you will be able to save 16-bit RGB output.
