### ISSUE TITLE
[Instructions issue] Meson needs installed via pip on ubuntu 22.04

### ISSUE THREAD

**Issue by nbaldy** [raspberrypi/rpicam-apps#649]
This might be silly because I haven't used meson before, but the version installed on Ubuntu 22.04 currently is meson_0.61.2-1; which does not allow us to build the rpicam-apps project because it requires 0.64.0 or newer. So the default apt install command doesn't work to compile the project. 

I got it working (well, further, but I don't think it's related) with the following, recommended by the meson install guide
```
pip3 install --user meson
PATH=$PATH:/home/hb-bird-cm4/.local/bin/
```
verified with 
```
$ meson --version
1.3.2
```

Submitting as an issue so that anyone else who runs into it can consider the fix.

**Comment by nbaldy** [comment]
Closing because it works - but this way it's referencable

**Comment by nbaldy** [comment]
Edit: meson should be installed via pip with sudo because it needs added to the sudo pythonpath for the ninja build of libcamera. 

### Ubuntu 22.04 alterations
- libcamera-apps is not distributed as an ubuntu-22.04 debian (See https://github.com/raspberrypi/rpicam-apps/issues/388). Needs built from source. See https://www.raspberrypi.com/documentation/computers/camera_software.html#building-libcamera
   - In the step `sudo apt install -y meson cmake`, if the current provided Ubuntu 22.04 meson is not newer than 0.64.0, install using an alternate package manager like pip. If using pip, must install via sudo and add `/home/<user>/.local/bin/` to PATH.

**Comment by fnndyl** [comment]
Another note to any future viewers, I also had to install ninja-build manually when installing meson using pip. May have been a me-specific issue though.
