### ISSUE TITLE
[BUG] Camera frontend has timed out

### ISSUE THREAD

**Issue by oliviacarino** [raspberrypi/rpicam-apps#650]
**Describe the bug**
When running `libcamera-hello` or even `libcamera-jpeg`, even though the camera is able to be detected. I get an error stating: 
`Dequeue timer of 5000000.00us has expired! ERROR: Camera frontend has timed out!`

**Bug report**
Please use the ``camera-bug-report`` tool to create a bug report, and upload it here.
- Command used for `bug.txt:` `camera-bug-report -t 5 -o bug.txt -c "rpicam-still -t 1000 -o test.jpg"`
[bug.txt](https://github.com/raspberrypi/rpicam-apps/files/14381093/bug.txt)

- Command used for `bug2.txt`: `camera-bug-report -o bug.txt -c "rpicam-vid -t 0 -o test.264"`
[bug2.txt](https://github.com/raspberrypi/rpicam-apps/files/14381089/bug2.txt)

**Additional context**
What I have tried so far to try and fix the issue:
**I have tried the following Pi's:**
Pi 3A+
Pi 4B

**I have tried the following cameras:**
Raspberry Pi Camera Module V3
Raspberry Pi Camera Module V3 NoIR

**I have tried the following OS systems using their latest, stable versions:**
Bullseye
Bookworm

I tried a combination of all of the above with each other and continued to get the same error that many other people have mentioned with the V3 cameras. I tried setting my camera timeout to be 5s and even 10s. Sadly, this did not work. I have installed fresh images of each OS multiple times when testing with each Pi, ran `apt update` and `apt upgrade`, this did not fix the issue either. Both cameras had the same error on both Pis and both OS (_please note, I tried each OS and cameras in different combinations on each Pi_).

I even tried turning on Glamor for the Pi 3, changing the gpu-memory on the Pi 3 to 256, and both things did not help :/ so I ended up buying a Pi 4B thinking it was a memory issue, but alas, it was not. I also confirmed that I was using the correct `dtoverlay` was used and `camera_auto_detect=1` was set within the config.txt file. The dtoverlays I tried were: vc4-fkms-v3d, vc4-kms-v3d, and imx708.

Reseating each camera multiple times didn't work either.

I am also using a verified Raspberry Pi USB-C 15W power supply.

**Comment by oliviacarino** [comment]
- No other peripherals are attached.
- I am using the 200mm connector cable that came with the camera.
- I am simply running it on my desk. I'm not using any housing for the pi itself, it just sits directly on my desk.

**Comment by naushir** [comment]
I'm afraid I don't have any further suggestions.  We've been trying to reproduce this ourselves, but have had boards running for > 24 hours without showing any timeouts.

**Comment by naushir** [comment]
Unfortunately I'll have to close as not-reproducible.  Similar to https://github.com/raspberrypi/picamera2/issues/952.

**Comment by phantum29** [comment]
@oliviacarino Did you ever get this resolved? I've been dealing with this for a while and finally decided to search for `Camera frontend has timed out!` dmesg also shows 
```
[   46.352011] edt_ft5x06 10-0038: Unable to fetch data, error: -5
[   52.979231] edt_ft5x06 10-0038: Unable to fetch data, error: -5
[   54.013809] i2c-bcm2835 fe205000.i2c: i2c transfer timed out
[   54.013840] edt_ft5x06 10-0038: Unable to fetch data, error: -110
[   54.014202] edt_ft5x06 10-0038: Unable to fetch data, error: -5
```
Maybe has something to do with our 'long' ribbon cables? Pi CM4 - Pi Cam v3, Bullseye. Tried all of the same things you have as well.

**Comment by oliviacarino** [comment]
@phantum29 nope, I just gave up lol. Ended up going the route of using an OpenMV Cam and ESP-01s I had lying around to do the same project. Super disappointed, but is what it is I suppose.

I actually tried a super short ribbon cable (I assumed the same thing about the length potentially being an issue). Still had no luck. Tried with multiple Pis as well.

**Comment by mkjena1512-star** [comment]
> **Describe the bug** When running `libcamera-hello` or even `libcamera-jpeg`, even though the camera is able to be detected. I get an error stating: `Dequeue timer of 5000000.00us has expired! ERROR: Camera frontend has timed out!`
> 
> **Bug report** Please use the `camera-bug-report` tool to create a bug report, and upload it here.
> 
> * Command used for `bug.txt:` `camera-bug-report -t 5 -o bug.txt -c "rpicam-still -t 1000 -o test.jpg"`
>   [bug.txt](https://github.com/raspberrypi/rpicam-apps/files/14381093/bug.txt)
> * Command used for `bug2.txt`: `camera-bug-report -o bug.txt -c "rpicam-vid -t 0 -o test.264"`
>   [bug2.txt](https://github.com/raspberrypi/rpicam-apps/files/14381089/bug2.txt)
> 
> **Additional context** What I have tried so far to try and fix the issue: **I have tried the following Pi's:** Pi 3A+ Pi 4B
> 
> **I have tried the following cameras:** Raspberry Pi Camera Module V3 Raspberry Pi Camera Module V3 NoIR
> 
> **I have tried the following OS systems using their latest, stable versions:** Bullseye Bookworm
> 
> I tried a combination of all of the above with each other and continued to get the same error that many other people have mentioned with the V3 cameras. I tried setting my camera timeout to be 5s and even 10s. Sadly, this did not work. I have installed fresh images of each OS multiple times when testing with each Pi, ran `apt update` and `apt upgrade`, this did not fix the issue either. Both cameras had the same error on both Pis and both OS (_please note, I tried each OS and cameras in different combinations on each Pi_).
> 
> I even tried turning on Glamor for the Pi 3, changing the gpu-memory on the Pi 3 to 256, and both things did not help :/ so I ended up buying a Pi 4B thinking it was a memory issue, but alas, it was not. I also confirmed that I was using the correct `dtoverlay` was used and `camera_auto_detect=1` was set within the config.txt file. The dtoverlays I tried were: vc4-fkms-v3d, vc4-kms-v3d, and imx708.
> 
> Reseating each camera multiple times didn't work either.
> 
> I am also using a verified Raspberry Pi USB-C 15W power supply.

facing the same issue , tried replacing the connecting cable still didn't work
