### ISSUE TITLE
Live change of roi

### ISSUE THREAD

**Issue by smzahraee** [raspberrypi/rpicam-apps#657]
I need to change the roi like camera digital zooms.
Is it possible to do that with rpicam-vid?

**Comment by smzahraee** [comment]
Thank you.
so as you said it is possible to change the roi at runtime. but I need to write an application shim.
Is there any documentation or example to start with that?
I want to develop with c++

**Comment by naushir** [comment]
You can look at the example on how we capture key presses here: https://github.com/raspberrypi/rpicam-apps/blob/1f2f08af358386437c0acf6a5112398595e0b2b4/apps/rpicam_vid.cpp#L28

You can create an app to capture a key and on the press event set the roi control maybe.
