### ISSUE TITLE
post-processing 3channels available?? there's only 1 channel

### ISSUE THREAD

**Issue by bert13069598** [raspberrypi/rpicam-apps#665]
[post-processing](https://www.raspberrypi.com/documentation/computers/camera_software.html#post-processing)

i want to make inrange post processing for my project.

but from sobel example, buffer only get 1 channel, and other examples too..
```c++
	StreamInfo info = app_->GetStreamInfo(stream_);
	BufferWriteSync w(app_, completed_request->buffers[stream_]);
	libcamera::Span<uint8_t> buffer = w.Get()[0];
	uint8_t *ptr = (uint8_t *)buffer.data();

	//Everything beyond this point is image processing...

	uint8_t value = 128;
	int num = (info.stride * info.height) / 2;
	Mat src = Mat(info.height, info.width, CV_8U, ptr, info.stride);
```
anyone know how to use 3 channel??

**Comment by naushir** [comment]
There are 3 channels (YUV) in a planar memory layout.  So Y is at offset ``0``, U is at offset ``width x height``, and V is at offset ``width x height / 2``.
