### ISSUE TITLE
Feature request: functionality to set camera focus while recording

### ISSUE THREAD

**Issue by ebner** [raspberrypi/rpicam-apps#667]
I am using a RPi Camera Module 3 (NoIR) with a RPi 3B+ and Debian 12. Due to low light conditions and a very close macro situation (10-15 cm distance to object) I cannot use the camera's autofocus functionality as it causes a lot of focus pumping.

The recorded object sometimes changes position which makes occasional refocusing necessary. This is for a live stream and I don't want to interrupt the recording session just to refocus. Instead, I would like to be able to trigger either a one-time autofocus or a full manual refocus without interrupting the recording.

While researching this topic I found some references that stated that `v4l2-ctl` could be used to set the focus (e.g. `v4l2-ctl -d /dev/v4l-subdev1 -c focus_absolute=<int>`), but this does not seem to work (anymore?).

Is there currently any way of changing focus while recording?

**Comment by naushir** [comment]
This is correct, there is no way to change the focus (and other controls) "live" while the application is running.  We currently don't have any plans to add such functionality.  The `rpicam-apps`` are written as non-interactive demo apps, and adding such functionality will introduce lots of complications.

For such use-cases we highly recommend using picamera2 which easily allows such interactive controls.  Or alternately you can create a new ``rpicam-apps`` application that is designed to handle interactive controls.
