### ISSUE TITLE
[BUG] rpicam-jpeg option parsing is broken for --datetime 

### ISSUE THREAD

**Issue by andreby** [raspberrypi/rpicam-apps#698]
rpicam-jpeg still asks for ```--output``` even when  ```--datetime``` is specified. 

The same options works when applied to rpicam-still.

Reading the ```--help``` output for both commands makes me think that ```--datetime``` should work the same.

```
# broken for rpicam-jpeg
root@z1:~# rpicam-jpeg --datetime --verbose 0 --nopreview
ERROR: *** output file name required ***

# same options works for rpicam-still
root@z1:~# rpicam-still --datetime --verbose 0 --nopreview

# versions
root@z1:~# uname -a
Linux z1 6.6.31+rpt-rpi-v7 #1 SMP Raspbian 1:6.6.31-1+rpt1 (2024-05-29) armv7l GNU/Linux

root@z1:~# rpicam-still --version
rpicam-apps build: 49344f2a8d18 17-06-2024 (12:19:10)
libcamera build: v0.3.0+65-6ddd79b5

root@z1:~# rpicam-jpeg --version
rpicam-apps build: 49344f2a8d18 17-06-2024 (12:19:10)
libcamera build: v0.3.0+65-6ddd79b5
```

**Comment by naushir** [comment]
``rpicam-jpeg`` is a very simple example app.  It does not support the ``--datetime`` feature.  You are right that the ``--help`` suggests it does, but that will be changed.  In the meantime, I suggest you stick with ``rpicam-still`` instead.
