### ISSUE TITLE
[BUG] Start to experience high rate of frame dropping after latest update (v0.3.1+50-69a894c4)

### ISSUE THREAD

**Issue by EwingKang** [raspberrypi/rpicam-apps#721]
**Describe the bug**
Start to experience high rate of frame dropping after latest update (`v0.3.1+50-69a894c4`)

**Bug report**
[bugreport0.txt](https://github.com/user-attachments/files/17093715/bugreport0.txt)
[bugreport1.txt](https://github.com/user-attachments/files/17093714/bugreport1.txt)

**Additional context**
I'm using `rpicam-vid` to capture 2 cameras at the same time on a RPI5. I needed these two cameras to capture video in sync. Doing it by calling two instance of `rpicam-vid` does the job pretty well before without framedrop.
```bash
rpicam-vid --camera 0 $VIDOPT -o ${HOSTNAME}_cam0_${SUFFIX1}_${SUFFIX2} &> log_${HOSTNAME}cam0_$SUFFIX1_$DATETIMEFULL.txt &
rpicam-vid --camera 1 $VIDOPT -o ${HOSTNAME}_cam1_${SUFFIX1}_${SUFFIX2} &> log_${HOSTNAME}cam1_$SUFFIX1_$DATETIMEFULL.txt
```
I'm doing it with a very save setting of 1640*1232@15 FPS on a IMX219. (Previously I have tested the setting up to 1640*1232@25 fps without any issue) At this setting, the total CPU usage is < 65%
After the update `v0.3.1+50-69a894c4` random framedrop starts to appear quite frequently. The same 45 second, 15FPS video no longer gives a stable 668 frames, but varying between 668, 652, 659, 660, 663 frames.
I dropped the framerate to as low as 5, and tested with different bitrate, still seeing varying framerate.

**Comment by naushir** [comment]
Can you post a clip of the captured video showing frame drops at 15fps that I can inspect please?

**Comment by EwingKang** [comment]
@naushir Thanks for your response.
These are two videos comming from two RPIs. The left is the one with 660 frames, the right one is the 668 frames. I triggered capturing both rpi to within 10 ms accuracy. 
The cellphone screen is a **count down** timer. For 15 FPS, there should be 66 ms between each frame.

Here are 3 consecutive frames. Frame dropping occured between frame 2 and 3.
* 39.726
    ![image](https://github.com/user-attachments/assets/75a6be0d-d6b1-49b7-ae6d-7e57d96964d1)
* 39.792
    ![image](https://github.com/user-attachments/assets/41f6abfd-c35d-4d12-a0f1-eacddb4f3fbb)
* 39.859
    ![image](https://github.com/user-attachments/assets/27660026-04b3-436e-82a1-9be8b76a3852)
* The missing 8 frames (only stepping the right camera frames)
    ![image](https://github.com/user-attachments/assets/6f54527c-bf06-45f1-a2a2-6453ec28ab91)
    ![image](https://github.com/user-attachments/assets/f91be4ca-6b4e-4bec-a19f-e855c0c58c94)
    ![image](https://github.com/user-attachments/assets/71b45eb3-69db-4ce8-a29c-3daea206d3a0)
    ![image](https://github.com/user-attachments/assets/44a74539-481b-4c7e-87a3-84e25a35f534)
    ![image](https://github.com/user-attachments/assets/efa7400d-e056-4ee1-ab96-2f2b27d5748a)
    ![image](https://github.com/user-attachments/assets/3a22bdc3-1d95-468b-8842-8026c2db5d77)
    ![image](https://github.com/user-attachments/assets/2c1ffa4f-5d5e-466d-b490-f9a195034bb9)
    ![image](https://github.com/user-attachments/assets/0ac8bf4a-a565-44cd-a4b0-c9382d570b76)
* "Catch-up", notice the timestamp difference
    ![image](https://github.com/user-attachments/assets/97cd4758-45c1-4fc7-9e89-c5a42a110a8e)

**Comment by naushir** [comment]
Would you be able to post the actual video files so I can have a look at all the frame timestamps please?

**Comment by EwingKang** [comment]
@naushir I can only provide the camera that has missing frames at [this link](https://fico365-my.sharepoint.com/:v:/g/personal/ewing_kang_fic_com_tw/EdtJ-wAhaQRGl34ODGayaCoB8-3dX8PaHJJDRq9ogNTuDw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=fduP69)
Can't promise how long I can keep this link alive, though

**Comment by naushir** [comment]
From the video you linked, I only see a single frame glitch, this is at approx frame 600, where the system seems to stall for approx 600ms.  Every other frame time is between 66.6 - 67ms apart as you would expect.  This glitch produces a large set of frame drops, but I cannot see any frame drops in any of the preceding frames:

![image](https://github.com/user-attachments/assets/49bcfebe-2110-47a1-8bbf-b24329d5765b)

You can use [this](https://github.com/raspberrypi/rpicam-apps/blob/main/utils/timestamp.py) script to verify your results.  Perhaps some other effect is causing what you are seeing?

**Comment by naushir** [comment]
Are you saving to an sdcard or a faster medium? Wear on the sdcard may cause slowdowns like this when the system decides the flush the data into the card.  Another thing to try would be to add ``force_turbo=1`` to ``/boot/firmware/config.txt`` at the bottom of the file.  This will ensure no clock throttling will happen when you are running.

**Comment by EwingKang** [comment]
@naushir 
It seems like the culprit is, indeed, the SD card degradation. 
I can no longer see the frame-dropping behavior after setting the destination to an external SSD drive. Due to space limitations, I'll probably have to use ramdisk (tmpfs).
Thank you very much for the help!
I'm perplexed by the coincidence of the event! All 3 Pis start showing such behavior at the same time. Maybe the update happens to make my Kingston SD card reach its degradation limit. ;(

* Original behavior
    ![out](https://github.com/user-attachments/assets/e635d539-fee0-4f6c-b901-b2ef57a34334)

* By using ramdisk (tmpfs) as described [here](https://askubuntu.com/questions/597268/virtual-ram-folder-in-ubuntu)
    ![out](https://github.com/user-attachments/assets/98365029-02bd-4335-9816-f3d0d9996d3d)

P.S. It Seems like the ram-disk solution causes my CPU usage to become very high from the original 60% to >95%. I'll probably have to get an SSD Hat or something. Thanks for the help again.
