### ISSUE TITLE
[BUG] Build fails due to missing asset file

### ISSUE THREAD

**Issue by mjforan** [raspberrypi/rpicam-apps#731]
Hi @naushir,
In your recent commit, [meson.build](https://github.com/raspberrypi/rpicam-apps/commit/0dc32d26c8f2c82645f60528135e788dfb45ce3c#diff-da7c376ce9e855194dedfc87c635f024badb2665658d1a3e4a5a38af676186a5R55) references an asset file "hailo_yolov8_pose_and_inference.json" which does not exist. When I run `meson setup build` I get this error:
```
post_processing_stages/hailo/meson.build:53:4: ERROR: File /rpicam-apps/assets/hailo_yolov8_pose_and_inference.json does not exist.
```

**Comment by naushir** [comment]
Apologies, I accidently included that in my last commit.  I've reverted the change and (force) pushed to this tree.
