### ISSUE TITLE
[BUG] Build fails due to missing asset file

### ISSUE THREAD

**Issue by osamu620** [raspberrypi/rpicam-apps#744]
The missing asset file (#731) was fixed. However, now we can see 

https://github.com/raspberrypi/rpicam-apps/blob/f3fab87628d55d22f7e8ebe12729ecc5e0e8eda1/post_processing_stages/hailo/meson.build#L50

I think this line should be removed.

**Comment by naushir** [comment]
Sorry, this got added by mistake.  I've now removed it.
